Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/precise64"
    config.vm.network "private_network", type: "dhcp", :adapter => "2"
    config.vm.provider "vmware_desktop" do |v|
        v.memory = 1024
        v.cpus = 1
    end
end

  